{\reset@font\mtcSfont\mtc@string\contentsline{section}{\noexpand \leavevmode \numberline {3.1}Trabajos previos de referencia}{\reset@font\mtcSfont 7}{section.3.1}}
{\reset@font\mtcSfont\mtc@string\contentsline{section}{\noexpand \leavevmode \numberline {3.2}Problemática detectada en la literatura}{\reset@font\mtcSfont 9}{section.3.2}}
{\reset@font\mtcSfont\mtc@string\contentsline{section}{\noexpand \leavevmode \numberline {3.3}Contribución de este trabajo}{\reset@font\mtcSfont 11}{section.3.3}}
