{\reset@font\mtcSfont\mtc@string\contentsline{section}{\noexpand \leavevmode \numberline {4.1}Especificaciones Hardware y Software}{\reset@font\mtcSfont 14}{section.4.1}}
{\reset@font\mtcSfont\mtc@string\contentsline{section}{\noexpand \leavevmode \numberline {4.2}Definición del problema}{\reset@font\mtcSfont 15}{section.4.2}}
{\reset@font\mtcSSfont\mtc@string\contentsline{subsection}{\noexpand \leavevmode \numberline {4.2.1}Dataset}{\reset@font\mtcSSfont 15}{subsection.4.2.1}}
{\reset@font\mtcSSfont\mtc@string\contentsline{subsection}{\noexpand \leavevmode \numberline {4.2.2}Matriz de haplotipos y \textit {Tag SNPs}}{\reset@font\mtcSSfont 16}{subsection.4.2.2}}
{\reset@font\mtcSSfont\mtc@string\contentsline{subsection}{\noexpand \leavevmode \numberline {4.2.3}Distinguibilidad}{\reset@font\mtcSSfont 16}{subsection.4.2.3}}
{\reset@font\mtcSSfont\mtc@string\contentsline{subsection}{\noexpand \leavevmode \numberline {4.2.4}Preprocesamiento: Eliminación de SNPs monomórficos}{\reset@font\mtcSSfont 17}{subsection.4.2.4}}
{\reset@font\mtcSSfont\mtc@string\contentsline{subsection}{\noexpand \leavevmode \numberline {4.2.5}Representación cromosómica de las soluciones}{\reset@font\mtcSSfont 18}{subsection.4.2.5}}
{\reset@font\mtcSfont\mtc@string\contentsline{section}{\noexpand \leavevmode \numberline {4.3}Objetivos Absolutos y Proporcionales}{\reset@font\mtcSfont 19}{section.4.3}}
{\reset@font\mtcSSfont\mtc@string\contentsline{subsection}{\noexpand \leavevmode \numberline {4.3.1}Formulación Absoluta}{\reset@font\mtcSSfont 19}{subsection.4.3.1}}
{\reset@font\mtcSSfont\mtc@string\contentsline{subsection}{\noexpand \leavevmode \numberline {4.3.2}Formulación Proporcional}{\reset@font\mtcSSfont 20}{subsection.4.3.2}}
{\reset@font\mtcSSfont\mtc@string\contentsline{subsection}{\noexpand \leavevmode \numberline {4.3.3}Transformación a minimización}{\reset@font\mtcSSfont 21}{subsection.4.3.3}}
{\reset@font\mtcSSfont\mtc@string\contentsline{subsection}{\noexpand \leavevmode \numberline {4.3.4}Factibilidad de individuos}{\reset@font\mtcSSfont 21}{subsection.4.3.4}}
{\reset@font\mtcSfont\mtc@string\contentsline{section}{\noexpand \leavevmode \numberline {4.4}Algoritmos evolutivos seleccionados}{\reset@font\mtcSfont 22}{section.4.4}}
{\reset@font\mtcSSfont\mtc@string\contentsline{subsection}{\noexpand \leavevmode \numberline {4.4.1}Algoritmos basados en dominancia de Pareto}{\reset@font\mtcSSfont 22}{subsection.4.4.1}}
{\reset@font\mtcSSfont\mtc@string\contentsline{subsection}{\noexpand \leavevmode \numberline {4.4.2}Algoritmos basados en métricas}{\reset@font\mtcSSfont 23}{subsection.4.4.2}}
{\reset@font\mtcSSfont\mtc@string\contentsline{subsection}{\noexpand \leavevmode \numberline {4.4.3}Algoritmos basados en descomposición y puntos de referencia}{\reset@font\mtcSSfont 23}{subsection.4.4.3}}
{\reset@font\mtcSSfont\mtc@string\contentsline{subsection}{\noexpand \leavevmode \numberline {4.4.4}Algoritmos basados en geometría de proximidad}{\reset@font\mtcSSfont 24}{subsection.4.4.4}}
{\reset@font\mtcSfont\mtc@string\contentsline{section}{\noexpand \leavevmode \numberline {4.5}Estrategias de inicialización}{\reset@font\mtcSfont 24}{section.4.5}}
{\reset@font\mtcSfont\mtc@string\contentsline{section}{\noexpand \leavevmode \numberline {4.6}Selección de operadores genéticos de cruce}{\reset@font\mtcSfont 31}{section.4.6}}
{\reset@font\mtcSfont\mtc@string\contentsline{section}{\noexpand \leavevmode \numberline {4.7}Diseño experimental}{\reset@font\mtcSfont 33}{section.4.7}}
{\reset@font\mtcSSfont\mtc@string\contentsline{subsection}{\noexpand \leavevmode \numberline {4.7.1}Configuración de hiperparámetros comunes}{\reset@font\mtcSSfont 33}{subsection.4.7.1}}
{\reset@font\mtcSSfont\mtc@string\contentsline{subsection}{\noexpand \leavevmode \numberline {4.7.2}Factores de variación}{\reset@font\mtcSSfont 34}{subsection.4.7.2}}
{\reset@font\mtcSSfont\mtc@string\contentsline{subsection}{\noexpand \leavevmode \numberline {4.7.3}Normalización}{\reset@font\mtcSSfont 35}{subsection.4.7.3}}
{\reset@font\mtcSSfont\mtc@string\contentsline{subsection}{\noexpand \leavevmode \numberline {4.7.4}Métricas de evaluación}{\reset@font\mtcSSfont 37}{subsection.4.7.4}}
{\reset@font\mtcSSfont\mtc@string\contentsline{subsection}{\noexpand \leavevmode \numberline {4.7.5}Análisis estadístico}{\reset@font\mtcSSfont 39}{subsection.4.7.5}}
